- name: check all server
  hosts: all
  tasks:
    - name: get current time
      shell: date +"%Y%m%d%H%M"
      register: current_time
      changed_when: false

    - name: check current time
      assert:
        fail_msg: "サーバ間の時刻に差があります。各サーバの時刻を揃えてください。"
        that:
          - current_time.stdout|int <= local_current_time|int + 1
          - current_time.stdout|int >= local_current_time|int - 1

    - name: check os
      assert:
        fail_msg: "OSは Ubuntu 16.04 以上を使用してください。"
        success_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
        that:
          - ansible_distribution == 'Ubuntu'
          - ansible_distribution_version|float >= 16.04

- name: check kqi node
  hosts: kqi-node
  roles:
    - role: precheck
      vars:
        cpu: 4
        memory: 8

  tasks:
    - name: get /var/lib available
      shell: df /var/lib | tail -1 | awk '{print $4}'
      register: var_lib_available
      changed_when: false

    - name: check /var/lib available
      assert:
        fail_msg: "/var/lib 配下には 10GB 以上の空き容量が必要です。"
        that:
          - var_lib_available.stdout|int >= 10 * 1024 * 1024

- name: check kubernetes master
  hosts: kube-master
  roles:
    - role: precheck
      vars:
        cpu: 2
        memory: 2

- name: check object storage
  hosts: object-storage
  roles:
    - role: precheck
      vars:
        cpu: 1
        memory: 2

- name: check gpu node
  hosts: gpu-node
  roles:
    - role: precheck
      vars:
        cpu: 2
        memory: 2

  tasks:
    - name: nvidia-smi works correctly
      shell: "test $(nvidia-smi -L | wc -l) -gt 0"
      changed_when: false