ingress:
  controller:
    nodeSelector:
      kubernetes.io/hostname: "kqi-node1"
    hostNetwork: true

virtualHosts:
  - "kqi-node1"

kqi_node: "kqi-node1"

resources:
  platypus_web_api:
    cpu: 5
    memory: 2048Mi
  platypus_web_pages:
    cpu: 0.3
    memory: 512Mi
  postgres:
    cpu: 5
    memory: 3096Mi

appsettings:
  ActiveDirectoryOptions__Domain: "my-org.my-corp.co.local"
  ActiveDirectoryOptions__BaseDn: "DC=my-org,DC=my-corp,DC=co,DC=local"
  ActiveDirectoryOptions__BaseOu: "\"\""
  ActiveDirectoryOptions__Server: "ad01"
  BackupPostgresTimerOptions__WeeklyTimeSchedule: "Sun=01:00:00"
  BackupPostgresTimerOptions__MaxNumberOfBackupFiles: "1"