FROM tensorflow/tensorflow:2.9.0-gpu

RUN pip install --upgrade pip \
    && pip install jupyterlab \
    && pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113