apiVersion: v1
kind: Secret
metadata:
  name: postgres-credential
  namespace: kqi-system
type: Opaque
data:
  POSTGRES_PASSWORD: "{{ .Values.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credential
  namespace: kqi-system
type: Opaque
data:
  MINIO_SECRET_KEY: "{{.Values.storage_secretkey | b64enc}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: platypus-web-api-env-secret
  namespace: kqi-system
type: Opaque
data:
  ConnectionStrings__DefaultConnection: {{ printf "Server=postgres;Port=5432;User Id=platypus;Password=%s;Database=platypusdb;Integrated Security=False;Timeout=30" .Values.db_password | b64enc }}
  DeployOptions__Password: "{{.Values.password | b64enc}}"
  DeployOptions__ObjectStorageSecretKey: "{{.Values.storage_secretkey | b64enc}}"