# coding: utf-8

"""
    KAMONOHASHI API

    A platform for deep learning  # noqa: E501

    OpenAPI spec version: v1
    Contact: kamonohashi-support@jp.nssol.nipponsteel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InfosStorageFileInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_name': 'str',
        'key': 'str',
        'last_modified': 'datetime',
        'size': 'int',
        'url': 'str'
    }

    attribute_map = {
        'file_name': 'fileName',
        'key': 'key',
        'last_modified': 'lastModified',
        'size': 'size',
        'url': 'url'
    }

    def __init__(self, file_name=None, key=None, last_modified=None, size=None, url=None):  # noqa: E501
        """InfosStorageFileInfo - a model defined in Swagger"""  # noqa: E501

        self._file_name = None
        self._key = None
        self._last_modified = None
        self._size = None
        self._url = None
        self.discriminator = None

        if file_name is not None:
            self.file_name = file_name
        if key is not None:
            self.key = key
        if last_modified is not None:
            self.last_modified = last_modified
        if size is not None:
            self.size = size
        if url is not None:
            self.url = url

    @property
    def file_name(self):
        """Gets the file_name of this InfosStorageFileInfo.  # noqa: E501


        :return: The file_name of this InfosStorageFileInfo.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this InfosStorageFileInfo.


        :param file_name: The file_name of this InfosStorageFileInfo.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def key(self):
        """Gets the key of this InfosStorageFileInfo.  # noqa: E501


        :return: The key of this InfosStorageFileInfo.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this InfosStorageFileInfo.


        :param key: The key of this InfosStorageFileInfo.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def last_modified(self):
        """Gets the last_modified of this InfosStorageFileInfo.  # noqa: E501


        :return: The last_modified of this InfosStorageFileInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this InfosStorageFileInfo.


        :param last_modified: The last_modified of this InfosStorageFileInfo.  # noqa: E501
        :type: datetime
        """

        self._last_modified = last_modified

    @property
    def size(self):
        """Gets the size of this InfosStorageFileInfo.  # noqa: E501


        :return: The size of this InfosStorageFileInfo.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this InfosStorageFileInfo.


        :param size: The size of this InfosStorageFileInfo.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def url(self):
        """Gets the url of this InfosStorageFileInfo.  # noqa: E501


        :return: The url of this InfosStorageFileInfo.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this InfosStorageFileInfo.


        :param url: The url of this InfosStorageFileInfo.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InfosStorageFileInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfosStorageFileInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
