# coding: utf-8

"""
    KAMONOHASHI API

    A platform for deep learning  # noqa: E501

    OpenAPI spec version: v1
    Contact: kamonohashi-support@jp.nssol.nipponsteel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PreprocessingApiModelsEditInputModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cpu': 'int',
        'gpu': 'int',
        'memo': 'str',
        'memory': 'int',
        'name': 'str'
    }

    attribute_map = {
        'cpu': 'cpu',
        'gpu': 'gpu',
        'memo': 'memo',
        'memory': 'memory',
        'name': 'name'
    }

    def __init__(self, cpu=None, gpu=None, memo=None, memory=None, name=None):  # noqa: E501
        """PreprocessingApiModelsEditInputModel - a model defined in Swagger"""  # noqa: E501

        self._cpu = None
        self._gpu = None
        self._memo = None
        self._memory = None
        self._name = None
        self.discriminator = None

        if cpu is not None:
            self.cpu = cpu
        if gpu is not None:
            self.gpu = gpu
        if memo is not None:
            self.memo = memo
        if memory is not None:
            self.memory = memory
        if name is not None:
            self.name = name

    @property
    def cpu(self):
        """Gets the cpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501


        :return: The cpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :rtype: int
        """
        return self._cpu

    @cpu.setter
    def cpu(self, cpu):
        """Sets the cpu of this PreprocessingApiModelsEditInputModel.


        :param cpu: The cpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :type: int
        """

        self._cpu = cpu

    @property
    def gpu(self):
        """Gets the gpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501


        :return: The gpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :rtype: int
        """
        return self._gpu

    @gpu.setter
    def gpu(self, gpu):
        """Sets the gpu of this PreprocessingApiModelsEditInputModel.


        :param gpu: The gpu of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :type: int
        """

        self._gpu = gpu

    @property
    def memo(self):
        """Gets the memo of this PreprocessingApiModelsEditInputModel.  # noqa: E501


        :return: The memo of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :rtype: str
        """
        return self._memo

    @memo.setter
    def memo(self, memo):
        """Sets the memo of this PreprocessingApiModelsEditInputModel.


        :param memo: The memo of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :type: str
        """

        self._memo = memo

    @property
    def memory(self):
        """Gets the memory of this PreprocessingApiModelsEditInputModel.  # noqa: E501


        :return: The memory of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :rtype: int
        """
        return self._memory

    @memory.setter
    def memory(self, memory):
        """Sets the memory of this PreprocessingApiModelsEditInputModel.


        :param memory: The memory of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :type: int
        """

        self._memory = memory

    @property
    def name(self):
        """Gets the name of this PreprocessingApiModelsEditInputModel.  # noqa: E501


        :return: The name of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PreprocessingApiModelsEditInputModel.


        :param name: The name of this PreprocessingApiModelsEditInputModel.  # noqa: E501
        :type: str
        """
        if name is not None and not re.search(r'^[^,!=<>][^,]*$', name):  # noqa: E501
            raise ValueError(r"Invalid value for `name`, must be a follow pattern or equal to `/^[^,!=<>][^,]*$/`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PreprocessingApiModelsEditInputModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreprocessingApiModelsEditInputModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
