apiVersion: apps/v1
kind: Deployment
metadata:
  name: platypus-web-pages
  namespace: kqi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platypus-web-pages
  template:
    metadata:
      name: platypus-web-pages
      labels:
        app: platypus-web-pages
    spec:
      serviceAccountName: platypus
      nodeSelector:
{{if .Values.kqi_node}}
        kubernetes.io/hostname: {{ .Values.kqi_node }}
{{ else }}
{{ toYaml .Values.platypus_web_pages.nodeSelector | indent 8 }}
{{end}}        
      volumes:
      - name: ntp
        hostPath:
          path: /etc/localtime  
      containers:
        - name: platypus-web-pages
          image: kamonohashi/web-pages:{{ .Values.image_tag | default .Chart.Version }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ .Values.resources.platypus_web_pages.cpu }}
              memory: {{ .Values.resources.platypus_web_pages.memory }}
            requests:
              cpu: {{ .Values.resources.platypus_web_pages.cpu }}
              memory: {{ .Values.resources.platypus_web_pages.memory }}
          volumeMounts:
            - mountPath: /etc/localtime
              name: ntp
              readOnly: true
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: platypus-web-pages
  namespace: kqi-system
spec:
  selector:
   app: platypus-web-pages
  ports:
    - port: 8080
      targetPort: 8080
      name: platypus-web-pages
